### ISSUE TITLE
PHP Fatal error:  Call to undefined method Twig_Function_Method::getPreEscape()

### ISSUE THREAD

**Issue by muhammadtaqi** [twigphp/Twig#2457]
Hi I'm getting this errror all of sudden with no updates in packages
`
PHP Fatal error:  Call to undefined method Twig_Function_Method::getPreEscape() in /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeVisitor/Escaper.php on line 109`

i `rm -rf vendor` and reinstall, still got same error.

The complete stacktrace;

HP Fatal error:  Call to undefined method Twig_Function_Method::getPreEscape() in /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeVisitor/Escaper.php on line 109
PHP Stack trace:
```
PHP   1. {main}() /var/www/notifiation_service/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/notifiation_service/app/console:22
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:898
PHP   7. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:244
PHP   8. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:83
PHP   9. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:120
PHP  10. Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheCacheWarmer->warmUp() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:47
PHP  11. Twig_Environment->loadTemplate() /var/www/notifiation_service/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php:62
PHP  12. Twig_Environment->compileSource() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/Environment.php:334
PHP  13. Twig_Environment->parse() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/Environment.php:559
PHP  14. Twig_Parser->parse() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/Environment.php:507
PHP  15. Twig_NodeTraverser->traverse() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/Parser.php:118
PHP  16. Twig_NodeTraverser->traverseForVisitor() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeTraverser.php:63
PHP  17. Twig_NodeTraverser->traverseForVisitor() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeTraverser.php:79
PHP  18. Twig_NodeTraverser->traverseForVisitor() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeTraverser.php:79
PHP  19. Twig_NodeTraverser->traverseForVisitor() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeTraverser.php:79
PHP  20. Twig_NodeTraverser->traverseForVisitor() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeTraverser.php:79
PHP  21. Twig_NodeTraverser->traverseForVisitor() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeTraverser.php:79
PHP  22. Twig_NodeTraverser->traverseForVisitor() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeTraverser.php:79
PHP  23. Twig_NodeVisitor_Escaper->leaveNode() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeTraverser.php:86
PHP  24. Twig_NodeVisitor_Escaper->preEscapeFilterNode() /var/www/notifiation_service/vendor/twig/twig/lib/Twig/NodeVisitor/Escaper.php:71
```
```
 twig/extensions                     v1.0.0             
 twig/twig                           v1.16.0 
```

> i also set autoescape = false in config. Still can't figure out why this error propping? Any hint?

**Comment by stof** [comment]
I suggest you to update Twig. 1.16 is several years old, and lots of bugs have been fixed in 1.x since then (we are at 1.33 currently)

**Comment by taqiofficial** [comment]
@stof I update the twig to `twig/twig :  1.x-dev ef680be and also v1.33.2`  but still the same error.

**Comment by taqiofficial** [comment]
What Functions or Filter's can cause this issue?

**Comment by stof** [comment]
I see a weird thing. It complains about a method on `Twig_Function_Method` when calling `preEscapeFilterNode`. But this one is about filters.

Could it be that you have an extension in your code using `Twig_Function_Method` to register a filter instead of `Twig_Filter_Method` ? Filters and functions are using different objects with different APIs. Using the wrong class may trigger such error.

**Comment by stof** [comment]
on a side note, `Twig_Function_Method` and `Twig_Filter_Method` are deprecated. You should migrate to `Twig_SimpleFunction` and `Twig_SimpleFilter`.

**Comment by taqiofficial** [comment]
Yes, It's registering filters like as ;

```
    public function getFunctions()
    {
        return array(
            'hasPDF' => new \Twig_Function_Method($this, 'hasPDF'),
            'line_break_replace' => new \Twig_Function_Method($this, 'lineBreakReplace'),
        );
    }
```

**Comment by stof** [comment]
I'm talking about registering a *filter*. So look at `getFilters` in all your extensions

**Comment by stof** [comment]
Btw, the naming `line_break_replace` let me think it should probably be a filter rather than a function.

**Comment by fabpot** [comment]
Closing as there is no more activity.
