### ISSUE TITLE
Warning in compiled Twig template

### ISSUE THREAD

**Issue by prudloff-insite** [twigphp/Twig#4022]
Since Twig 3.9.0, we get this warning on some of our templates:
> Warning: Undefined variable $blocks

This is the smallest example I could write:
```twig
{{ _self.mymacro(items, attributes, 0, menu_name) }}

{% macro mymacro(items, attributes, menu_level, menu_name) %}
  {% if items %}
    {% apply spaceless %}
      {% if menu_level == 0 %}
        foo
      {% endif %}
    {% endapply %}
  {% endif %}
{% endmacro %}
```
It seems to come from the code generated here: https://github.com/twigphp/Twig/blob/2105d659574211ce6da200da5867180a1e00c1ef/src/Node/CaptureNode.php#L39

Reverting back to Twig 3.8.0 removes the warning.

**Comment by tobias-93** [comment]
In one of the cases I could find, this seems to be related to a macro that is being wrapped in a tracing/profiling extension structure. For example:
```
    public function macro_bytesToSize($__bytes__ = null, ...$__varargs__)
    {
        $macros = $this->macros;
        $context = $this->env->mergeGlobals([
            "bytes" => $__bytes__,
            "varargs" => $__varargs__,
        ]);

        $blocks = []; // Blocks variable is set here

        return ('' === $tmp = \Twig\Extension\CoreExtension::captureOutput((function () use (&$context, $macros) { // Wrapping in a function without blocks variable
            $__internal_5a27a8ba21ca79b61932376b2fa922d2 = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
            $__internal_5a27a8ba21ca79b61932376b2fa922d2->enter($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "macro", "bytesToSize"));

            $__internal_b91a4435ea3baf1e2b6bfda56133dace = $this->extensions["Sentry\\SentryBundle\\Tracing\\Twig\\TwigTracingExtension"];
            $__internal_b91a4435ea3baf1e2b6bfda56133dace->enter($__internal_b91a4435ea3baf1e2b6bfda56133dace_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "macro", "bytesToSize"));

            $__internal_6f47bbe9983af81f1e7450e9a3e3768f = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
            $__internal_6f47bbe9983af81f1e7450e9a3e3768f->enter($__internal_6f47bbe9983af81f1e7450e9a3e3768f_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "macro", "bytesToSize"));

            // line 2
            $___internal_parse_0_ = ('' === $tmp = \Twig\Extension\CoreExtension::captureOutput((function () use (&$context, $macros, $blocks) { // No more blocks variable here, so warning is given
                // More code
            })() ?? new \EmptyIterator())) ? '' : new Markup($tmp, $this->env->getCharset());
            // line 2
            yield Twig\Extension\CoreExtension::spaceless($___internal_parse_0_);

            $__internal_6f47bbe9983af81f1e7450e9a3e3768f->leave($__internal_6f47bbe9983af81f1e7450e9a3e3768f_prof);


            $__internal_b91a4435ea3baf1e2b6bfda56133dace->leave($__internal_b91a4435ea3baf1e2b6bfda56133dace_prof);


            $__internal_5a27a8ba21ca79b61932376b2fa922d2->leave($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof);

        })() ?? new \EmptyIterator())) ? '' : new Markup($tmp, $this->env->getCharset());
    }
```
Not sure if this helps, but this is as far as I came this evening.

**Comment by fabpot** [comment]
@prudloff-insite @tobias-93 Can you confirm that #4023 fixes the issue?

**Comment by leofeyer** [comment]
We also have the problem and I can confirm that #4023 fixes it. Thank you @fabpot.

**Comment by tobias-93** [comment]
Hi @fabpot, #4023 fixes the issue for us. Thanks for the quick fix!

**Comment by frenchcomp** [comment]
Hi, i also have this problem, and the patch in #4023 fixes also it.
Thanks ou

**Comment by prudloff-insite** [comment]
I confirm https://github.com/twigphp/Twig/pull/4023 fixes our warning.

**Comment by fabpot** [comment]
I've just released 3.9.1 with the fix.

**Comment by jkgroupe** [comment]
I still have the issue with version 3.9.3 when I'm setting variable in cache tag

`An exception has been thrown during the rendering of a template ("Warning: Undefined variable $blocks").`

```
{% cache 'project_%s_%s'|format(project.id, project.updatedAt.timestamp) ttl(36000) %}
   {% set list %}
      <div class="list-group list-group-flush"></div>
   {% endset %}
   {{ list }}
{% endcache %}
```

![Capture d’écran 2024-05-07 à 16 12 41](https://github.com/twigphp/Twig/assets/4007104/4aeb50d7-491b-4ea1-afc3-b265b07b6b12)

**Comment by fabpot** [comment]
@jkgroupe Can you create a new issue so that it's not lost? Thank you.
