### ISSUE TITLE
blocks do not work in v3.9.0 - An exception has been thrown during the rendering of a template ("Warning: foreach() argument must be of type array|object, null given").

### ISSUE THREAD

**Issue by marvin-bilharz** [twigphp/Twig#4024]
![image](https://github.com/twigphp/Twig/assets/140318395/48b98fb6-340f-4709-9a43-ac10055aa04f)
An exception has been thrown during the rendering of a template ("Warning: foreach() argument must be of type array|object, null given").

All I did was updating to v3.9.0 from v3.8.0. After reversing everything works again.

All blocks in my template are not working anymore in the v3.9.0 release.

**Comment by fabpot** [comment]
Fixed in #4023

**Comment by fashxp** [comment]
sadly, still not working for us :disappointed: : 

![image](https://github.com/twigphp/Twig/assets/8792145/e9c09c25-fa1a-4977-a6ee-b6a9bd8dd56a)

when using twig v3.9.1
![image](https://github.com/twigphp/Twig/assets/8792145/8077bba6-8cd8-4f37-a317-b15063604a17)

**Comment by stof** [comment]
Please open an issue with a reproducer

**Comment by fashxp** [comment]
done, https://github.com/twigphp/Twig/issues/4026 ... thx.
