### ISSUE TITLE
Warning: Undefined variable $_v0 since 3.15

### ISSUE THREAD

**Issue by lpotherat** [twigphp/Twig#4480]
Hi, 

Since twig 3.15, the base layout of easyadmin ( vendor/easycorp/easyadmin-bundle/templates/layout.html.twig ) triggers a warning at line 108 of the template : `{{ item.label|trans }}` .

The warning tells that the $_v0 variable is undefined in the compiled version of the twig template, here is the line : 
```php
// line 108
yield "                                        ";
yield $this->env->getRuntime('Twig\Runtime\EscaperRuntime')->escape($this->extensions['Symfony\Bridge\Twig\Extension\TranslationExtension']->trans(CoreExtension::getAttribute($this->env, $this->source, $context["item"], "label", [], "any", false, false, false, 108), [], $_v0), "html", null, true);
yield "
```

And the full function from the compiled template : 
```php
// line 96
    /**
     * @return iterable<null|scalar|\Stringable>
     */
    public function block_user_menu(array $context, array $blocks = []): iterable
    {
        $macros = $this->macros;
        $__internal_5a27a8ba21ca79b61932376b2fa922d2 = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_5a27a8ba21ca79b61932376b2fa922d2->enter($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "block", "user_menu"));

        $__internal_6f47bbe9983af81f1e7450e9a3e3768f = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_6f47bbe9983af81f1e7450e9a3e3768f->enter($__internal_6f47bbe9983af81f1e7450e9a3e3768f_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "block", "user_menu"));

        // line 97
        yield "                    ";
        if ((Twig\Extension\CoreExtension::length($this->env->getCharset(), CoreExtension::getAttribute($this->env, $this->source, CoreExtension::getAttribute($this->env, $this->source, (isset($context["ea"]) || array_key_exists("ea", $context) ? $context["ea"] : (function () { throw new RuntimeError('Variable "ea" does not exist.', 97, $this->source); })()), "userMenu", [], "any", false, false, false, 97), "items", [], "any", false, false, false, 97)) > 0)) {
            // line 98
            yield "                        <li><hr class=\"dropdown-divider\"></li>
                        ";
            // line 99
            $context['_parent'] = $context;
            $context['_seq'] = CoreExtension::ensureTraversable(CoreExtension::getAttribute($this->env, $this->source, CoreExtension::getAttribute($this->env, $this->source, (isset($context["ea"]) || array_key_exists("ea", $context) ? $context["ea"] : (function () { throw new RuntimeError('Variable "ea" does not exist.', 99, $this->source); })()), "userMenu", [], "any", false, false, false, 99), "items", [], "any", false, false, false, 99));
            $context['loop'] = [
              'parent' => $context['_parent'],
              'index0' => 0,
              'index'  => 1,
              'first'  => true,
            ];
            if (is_array($context['_seq']) || (is_object($context['_seq']) && $context['_seq'] instanceof \Countable)) {
                $length = count($context['_seq']);
                $context['loop']['revindex0'] = $length - 1;
                $context['loop']['revindex'] = $length;
                $context['loop']['length'] = $length;
                $context['loop']['last'] = 1 === $length;
            }
            foreach ($context['_seq'] as $context["_key"] => $context["item"]) {
                // line 100
                yield "                            <li>
                                ";
                // line 101
                if ((CoreExtension::getAttribute($this->env, $this->source, $context["item"], "isMenuSection", [], "any", false, false, false, 101) &&  !CoreExtension::getAttribute($this->env, $this->source, $context["loop"], "first", [], "any", false, false, false, 101))) {
                    // line 102
                    yield "                                    <hr class=\"dropdown-divider\">
                                ";
                } elseif ( !CoreExtension::getAttribute($this->env, $this->source,                 // line 103
$context["item"], "isMenuSection", [], "any", false, false, false, 103)) {
                    // line 104
                    yield "                                    <a href=\"";
                    yield $this->env->getRuntime('Twig\Runtime\EscaperRuntime')->escape(CoreExtension::getAttribute($this->env, $this->source, $context["item"], "linkUrl", [], "any", false, false, false, 104), "html", null, true);
                    yield "\" class=\"dropdown-item user-action ";
                    yield $this->env->getRuntime('Twig\Runtime\EscaperRuntime')->escape(CoreExtension::getAttribute($this->env, $this->source, $context["item"], "cssClass", [], "any", false, false, false, 104), "html", null, true);
                    yield "\"
                                       target=\"";
                    // line 105
                    yield $this->env->getRuntime('Twig\Runtime\EscaperRuntime')->escape(CoreExtension::getAttribute($this->env, $this->source, $context["item"], "linkTarget", [], "any", false, false, false, 105), "html", null, true);
                    yield "\" rel=\"";
                    yield $this->env->getRuntime('Twig\Runtime\EscaperRuntime')->escape(CoreExtension::getAttribute($this->env, $this->source, $context["item"], "linkRel", [], "any", false, false, false, 105), "html", null, true);
                    yield "\"
                                       referrerpolicy=\"origin-when-cross-origin\">
                                        ";
                    // line 107
                    if ( !Twig\Extension\CoreExtension::testEmpty(CoreExtension::getAttribute($this->env, $this->source, $context["item"], "icon", [], "any", false, false, false, 107))) {
                        yield $this->env->getRuntime('Symfony\UX\TwigComponent\Twig\ComponentRuntime')->render("ea:Icon", ["name" => CoreExtension::getAttribute($this->env, $this->source, $context["item"], "icon", [], "any", false, false, false, 107)]);
                    }
                    // line 108
                    yield "                                        ";
                    yield $this->env->getRuntime('Twig\Runtime\EscaperRuntime')->escape($this->extensions['Symfony\Bridge\Twig\Extension\TranslationExtension']->trans(CoreExtension::getAttribute($this->env, $this->source, $context["item"], "label", [], "any", false, false, false, 108), [], $_v0), "html", null, true);
                    yield "
                                    </a>
                                ";
                }
                // line 111
                yield "                            </li>
                        ";
                ++$context['loop']['index0'];
                ++$context['loop']['index'];
                $context['loop']['first'] = false;
                if (isset($context['loop']['revindex0'], $context['loop']['revindex'])) {
                    --$context['loop']['revindex0'];
                    --$context['loop']['revindex'];
                    $context['loop']['last'] = 0 === $context['loop']['revindex0'];
                }
            }
            $_parent = $context['_parent'];
            unset($context['_seq'], $context['_key'], $context['item'], $context['_parent'], $context['loop']);
            $context = array_intersect_key($context, $_parent) + $_parent;
            // line 113
            yield "                    ";
        }
        // line 114
        yield "                ";
        
        $__internal_6f47bbe9983af81f1e7450e9a3e3768f->leave($__internal_6f47bbe9983af81f1e7450e9a3e3768f_prof);

        
        $__internal_5a27a8ba21ca79b61932376b2fa922d2->leave($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof);

        yield from [];
    }
```

I rolled back to 3.14.2 and all works again.

Thanks

**Comment by jdreesen** [comment]
Duplicate of #4452?

**Comment by xabbuh** [comment]
Does #4475 help?

**Comment by lpotherat** [comment]
Yes, #4452 has the exact same error in one of the comments, the issue title was not meaningful for my use case sorry !
I'm going to test it

**Comment by lpotherat** [comment]
I'm back, upgrading to "twig/twig": "3.x-dev#c384fb4d8cd4bfbca7a13f9d36e3afb53c4ed655" brings me to a Syntax error : 

An exception has been thrown during the compilation of a template ("EmptyNode cannot have children.")
![image](https://github.com/user-attachments/assets/18fa2717-26b5-4dbb-9dd0-cb4a0bdd0301)

I may not be the same issue ?
Rolling back to 3.14.2 again :)

**Comment by xabbuh** [comment]
for that you probably need symfony/symfony#58964 (i.e. the latest patch release of `symfony/twig-bridge` for the Symfony version you are using)

**Comment by lpotherat** [comment]
I'm currently on 7.2 RC1, I'll wait the next RC to update Twig then

**Comment by fabpot** [comment]
Closing as this has been fixed already as mentioned above.

**Comment by alexndlm** [comment]
@fabpot, the issue is still actual.

**Comment by xabbuh** [comment]
@alexndlm Please create a small application then that allows to reproduce it.

**Comment by alexndlm** [comment]
For now, I cannot create the Tets app. 

Could you please check this https://github.com/EasyCorp/EasyAdminBundle/actions/runs/12086509610/job/33705948788

The interesting thing is that for `dev` devs, it works.

**Comment by xabbuh** [comment]
That job installs version 7.1.0 of the Twig bridge which is probably the reason for the failure.

**Comment by alexndlm** [comment]
Got it, thanks.

And what about job with 6.4 - https://github.com/EasyCorp/EasyAdminBundle/actions/runs/12086509610/job/33705948476

**Comment by alexndlm** [comment]
Ohhhhhh. Got it. In that job exactly 6.4.0

**Comment by stof** [comment]
@alexndlm the jobs is asking for it: https://github.com/EasyCorp/EasyAdminBundle/actions/runs/12086509610/job/33705948476#step:6:1

`6.4` as version *constraint* only allows 6.4.0 as matching version.

**Comment by alexndlm** [comment]
Thanks. I finally got it.

**Comment by javiereguiluz** [comment]
@xabbuh after updating to the latest versions of all Symfony packages, I still see `An exception has been thrown during the rendering of a template ("Warning: Undefined variable $_v0").` issue but only in Symfony 7.2, not the previous versions.

I prepared the smallest possible reproducer:

* Clone `https://github.com/javiereguiluz/ea-bug-reproducer`
* Run `composer install`
* Run `php bin/console doctrine:database:create` (it's a SQLite database)
* Run `php bin/console doctrine:schema:create`
* Run `symfony serve -d`
* Visit `https://127.0.0.1:8001/admin`
 
You'll see this exception:

<details>
Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Warning: Undefined variable $_v0").

  at vendor/easycorp/easyadmin-bundle/templates/crud/index.html.twig:40
  at Twig\Template->yieldBlock('content_title', array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection), 'ea' => object(AdminContextProvider), 'app' => object(AppVariable), 'ea_field_assets' => object(AssetsDto), 'has_batch_actions' => true), array('head_metas' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_metas'), 'page_title' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_title'), 'head_stylesheets' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_stylesheets'), 'configured_stylesheets' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_stylesheets'), 'head_favicon' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_favicon'), 'head_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_javascript'), 'importmap' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_importmap'), 'configured_javascripts' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_javascripts'), 'configured_head_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_head_contents'), 'body' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body'), 'body_attr' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_attr'), 'body_id' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_id'), 'body_class' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_class'), 'javascript_page_layout' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_layout'), 'javascript_page_color_scheme' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_color_scheme'), 'wrapper_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper_wrapper'), 'flash_messages' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_flash_messages'), 'user_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_user_menu'), 'wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper'), 'responsive_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header'), 'responsive_header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header_logo'), 'sidebar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_sidebar'), 'header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header'), 'header_navbar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_navbar'), 'header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_logo'), 'main_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_main_menu_wrapper'), 'content_top_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_top_header'), 'search_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_wrapper'), 'search' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search'), 'search_form' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form'), 'search_form_filters' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form_filters'), 'header_custom_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu_wrapper'), 'header_custom_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu'), 'settings_dropdown_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_settings_dropdown_wrapper'), 'content' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content'), 'content_header_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header_wrapper'), 'content_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header'), 'content_title' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_content_title'), 'content_help' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_help'), 'page_actions_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_actions_wrapper'), 'page_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_page_actions'), 'main' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_main'), 'content_footer_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_footer_wrapper'), 'body_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_javascript'), 'configured_body_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_body_contents'), 'filters' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_filters'), 'global_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_global_actions'), 'batch_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_batch_actions'), 'table_head' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_head'), 'table_body' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body'), 'entity_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_entity_actions'), 'table_body_empty' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body_empty'), 'table_footer' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_footer'), 'paginator' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_paginator'), 'delete_form' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_delete_form')))
     (var/cache/dev/twig/98/98429a2e71318ee2f8afe3c02b60c7bb.php:208)
  at __TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421->block_page_title(array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection), 'ea' => object(AdminContextProvider), 'app' => object(AppVariable), 'ea_field_assets' => object(AssetsDto), 'has_batch_actions' => true), array('head_metas' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_metas'), 'page_title' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_title'), 'head_stylesheets' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_stylesheets'), 'configured_stylesheets' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_stylesheets'), 'head_favicon' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_favicon'), 'head_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_javascript'), 'importmap' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_importmap'), 'configured_javascripts' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_javascripts'), 'configured_head_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_head_contents'), 'body' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body'), 'body_attr' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_attr'), 'body_id' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_id'), 'body_class' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_class'), 'javascript_page_layout' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_layout'), 'javascript_page_color_scheme' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_color_scheme'), 'wrapper_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper_wrapper'), 'flash_messages' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_flash_messages'), 'user_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_user_menu'), 'wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper'), 'responsive_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header'), 'responsive_header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header_logo'), 'sidebar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_sidebar'), 'header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header'), 'header_navbar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_navbar'), 'header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_logo'), 'main_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_main_menu_wrapper'), 'content_top_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_top_header'), 'search_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_wrapper'), 'search' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search'), 'search_form' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form'), 'search_form_filters' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form_filters'), 'header_custom_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu_wrapper'), 'header_custom_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu'), 'settings_dropdown_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_settings_dropdown_wrapper'), 'content' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content'), 'content_header_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header_wrapper'), 'content_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header'), 'content_title' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_content_title'), 'content_help' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_help'), 'page_actions_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_actions_wrapper'), 'page_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_page_actions'), 'main' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_main'), 'content_footer_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_footer_wrapper'), 'body_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_javascript'), 'configured_body_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_body_contents'), 'filters' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_filters'), 'global_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_global_actions'), 'batch_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_batch_actions'), 'table_head' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_head'), 'table_body' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body'), 'entity_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_entity_actions'), 'table_body_empty' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body_empty'), 'table_footer' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_footer'), 'paginator' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_paginator'), 'delete_form' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_delete_form')))
     (vendor/twig/twig/src/Template.php:431)
  at Twig\Template->yieldBlock('page_title', array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection), 'ea' => object(AdminContextProvider), 'app' => object(AppVariable), 'ea_field_assets' => object(AssetsDto), 'has_batch_actions' => true), array('head_metas' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_metas'), 'page_title' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_title'), 'head_stylesheets' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_stylesheets'), 'configured_stylesheets' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_stylesheets'), 'head_favicon' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_favicon'), 'head_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_javascript'), 'importmap' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_importmap'), 'configured_javascripts' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_javascripts'), 'configured_head_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_head_contents'), 'body' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body'), 'body_attr' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_attr'), 'body_id' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_id'), 'body_class' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_class'), 'javascript_page_layout' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_layout'), 'javascript_page_color_scheme' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_color_scheme'), 'wrapper_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper_wrapper'), 'flash_messages' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_flash_messages'), 'user_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_user_menu'), 'wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper'), 'responsive_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header'), 'responsive_header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header_logo'), 'sidebar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_sidebar'), 'header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header'), 'header_navbar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_navbar'), 'header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_logo'), 'main_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_main_menu_wrapper'), 'content_top_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_top_header'), 'search_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_wrapper'), 'search' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search'), 'search_form' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form'), 'search_form_filters' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form_filters'), 'header_custom_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu_wrapper'), 'header_custom_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu'), 'settings_dropdown_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_settings_dropdown_wrapper'), 'content' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content'), 'content_header_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header_wrapper'), 'content_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header'), 'content_title' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_content_title'), 'content_help' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_help'), 'page_actions_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_actions_wrapper'), 'page_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_page_actions'), 'main' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_main'), 'content_footer_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_footer_wrapper'), 'body_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_javascript'), 'configured_body_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_body_contents'), 'filters' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_filters'), 'global_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_global_actions'), 'batch_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_batch_actions'), 'table_head' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_head'), 'table_body' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body'), 'entity_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_entity_actions'), 'table_body_empty' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body_empty'), 'table_footer' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_footer'), 'paginator' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_paginator'), 'delete_form' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_delete_form')))
     (var/cache/dev/twig/98/98429a2e71318ee2f8afe3c02b60c7bb.php:112)
  at __TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421->{closure}()
     (vendor/twig/twig/src/Extension/CoreExtension.php:2058)
  at Twig\Extension\CoreExtension::captureOutput(object(Generator))
     (var/cache/dev/twig/98/98429a2e71318ee2f8afe3c02b60c7bb.php:111)
  at __TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421->doDisplay(array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection), 'ea' => object(AdminContextProvider), 'app' => object(AppVariable), 'ea_field_assets' => object(AssetsDto), 'has_batch_actions' => true), array('head_metas' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_metas'), 'page_title' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_title'), 'head_stylesheets' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_stylesheets'), 'configured_stylesheets' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_stylesheets'), 'head_favicon' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_favicon'), 'head_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_javascript'), 'importmap' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_importmap'), 'configured_javascripts' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_javascripts'), 'configured_head_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_head_contents'), 'body' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body'), 'body_attr' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_attr'), 'body_id' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_id'), 'body_class' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_class'), 'javascript_page_layout' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_layout'), 'javascript_page_color_scheme' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_color_scheme'), 'wrapper_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper_wrapper'), 'flash_messages' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_flash_messages'), 'user_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_user_menu'), 'wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper'), 'responsive_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header'), 'responsive_header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header_logo'), 'sidebar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_sidebar'), 'header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header'), 'header_navbar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_navbar'), 'header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_logo'), 'main_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_main_menu_wrapper'), 'content_top_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_top_header'), 'search_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_wrapper'), 'search' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search'), 'search_form' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form'), 'search_form_filters' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form_filters'), 'header_custom_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu_wrapper'), 'header_custom_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu'), 'settings_dropdown_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_settings_dropdown_wrapper'), 'content' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content'), 'content_header_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header_wrapper'), 'content_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header'), 'content_title' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_content_title'), 'content_help' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_help'), 'page_actions_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_actions_wrapper'), 'page_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_page_actions'), 'main' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_main'), 'content_footer_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_footer_wrapper'), 'body_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_javascript'), 'configured_body_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_body_contents'), 'filters' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_filters'), 'global_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_global_actions'), 'batch_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_batch_actions'), 'table_head' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_head'), 'table_body' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body'), 'entity_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_entity_actions'), 'table_body_empty' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body_empty'), 'table_footer' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_footer'), 'paginator' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_paginator'), 'delete_form' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_delete_form')))
     (vendor/twig/twig/src/Template.php:387)
  at Twig\Template->yield(array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection), 'ea' => object(AdminContextProvider), 'app' => object(AppVariable), 'ea_field_assets' => object(AssetsDto), 'has_batch_actions' => true), array('head_metas' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_metas'), 'page_title' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_title'), 'head_stylesheets' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_stylesheets'), 'configured_stylesheets' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_stylesheets'), 'head_favicon' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_favicon'), 'head_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_head_javascript'), 'importmap' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_importmap'), 'configured_javascripts' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_javascripts'), 'configured_head_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_head_contents'), 'body' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body'), 'body_attr' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_attr'), 'body_id' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_id'), 'body_class' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_class'), 'javascript_page_layout' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_layout'), 'javascript_page_color_scheme' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_javascript_page_color_scheme'), 'wrapper_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper_wrapper'), 'flash_messages' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_flash_messages'), 'user_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_user_menu'), 'wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_wrapper'), 'responsive_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header'), 'responsive_header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_responsive_header_logo'), 'sidebar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_sidebar'), 'header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header'), 'header_navbar' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_navbar'), 'header_logo' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_logo'), 'main_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_main_menu_wrapper'), 'content_top_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_top_header'), 'search_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_wrapper'), 'search' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search'), 'search_form' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form'), 'search_form_filters' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_search_form_filters'), 'header_custom_menu_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu_wrapper'), 'header_custom_menu' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_header_custom_menu'), 'settings_dropdown_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_settings_dropdown_wrapper'), 'content' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content'), 'content_header_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header_wrapper'), 'content_header' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_header'), 'content_title' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_content_title'), 'content_help' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_help'), 'page_actions_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_page_actions_wrapper'), 'page_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_page_actions'), 'main' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_main'), 'content_footer_wrapper' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_content_footer_wrapper'), 'body_javascript' => array(object(__TwigTemplate_b9cd17cd5b40da14daa1a5898e4c8421), 'block_body_javascript'), 'configured_body_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_body_contents'), 'filters' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_filters'), 'global_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_global_actions'), 'batch_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_batch_actions'), 'table_head' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_head'), 'table_body' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body'), 'entity_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_entity_actions'), 'table_body_empty' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body_empty'), 'table_footer' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_footer'), 'paginator' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_paginator'), 'delete_form' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_delete_form')))
     (var/cache/dev/twig/99/99fc3d83a3ff07a30062991b4cfbcca6.php:77)
  at __TwigTemplate_2e80ab6c9932371d4c54e110d0460c99->doDisplay(array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection), 'ea' => object(AdminContextProvider), 'app' => object(AppVariable), 'ea_field_assets' => object(AssetsDto), 'has_batch_actions' => true), array('body_id' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_id'), 'body_class' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_class'), 'configured_head_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_head_contents'), 'configured_body_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_body_contents'), 'configured_stylesheets' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_stylesheets'), 'configured_javascripts' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_javascripts'), 'content_title' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_content_title'), 'page_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_page_actions'), 'filters' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_filters'), 'global_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_global_actions'), 'batch_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_batch_actions'), 'main' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_main'), 'table_head' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_head'), 'table_body' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body'), 'entity_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_entity_actions'), 'table_body_empty' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body_empty'), 'table_footer' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_footer'), 'paginator' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_paginator'), 'delete_form' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_delete_form')))
     (vendor/twig/twig/src/Template.php:387)
  at Twig\Template->yield(array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection), 'ea' => object(AdminContextProvider), 'app' => object(AppVariable)), array('body_id' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_id'), 'body_class' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_body_class'), 'configured_head_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_head_contents'), 'configured_body_contents' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_body_contents'), 'configured_stylesheets' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_stylesheets'), 'configured_javascripts' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_configured_javascripts'), 'content_title' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_content_title'), 'page_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_page_actions'), 'filters' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_filters'), 'global_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_global_actions'), 'batch_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_batch_actions'), 'main' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_main'), 'table_head' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_head'), 'table_body' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body'), 'entity_actions' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_entity_actions'), 'table_body_empty' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_body_empty'), 'table_footer' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_table_footer'), 'paginator' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_paginator'), 'delete_form' => array(object(__TwigTemplate_2e80ab6c9932371d4c54e110d0460c99), 'block_delete_form')))
     (vendor/twig/twig/src/Template.php:343)
  at Twig\Template->display(array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection)))
     (vendor/twig/twig/src/Template.php:358)
  at Twig\Template->render(array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection)))
     (vendor/twig/twig/src/TemplateWrapper.php:35)
  at Twig\TemplateWrapper->render(array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection)))
     (vendor/twig/twig/src/Environment.php:320)
  at Twig\Environment->render('@EasyAdmin/crud/index.html.twig', array('pageName' => 'index', 'templateName' => 'crud/index', 'entities' => object(EntityCollection), 'paginator' => object(EntityPaginator), 'global_actions' => object(ActionCollection), 'batch_actions' => object(ActionCollection), 'filters' => object(FilterCollection)))
     (vendor/easycorp/easyadmin-bundle/src/EventListener/CrudResponseListener.php:49)
  at EasyCorp\Bundle\EasyAdminBundle\EventListener\CrudResponseListener->onKernelView(object(ViewEvent), 'kernel.view', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ViewEvent), 'kernel.view', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener)), 'kernel.view', object(ViewEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ViewEvent), 'kernel.view')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:122)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ViewEvent), 'kernel.view')
     (vendor/symfony/http-kernel/HttpKernel.php:188)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:182)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('ea-bug-reproducer/vendor/autoload_runtime.php')
     (public/index.php:5)                
</details>

**Comment by fabpot** [comment]
@javiereguiluz Can you check that you have version 3.16.0?

**Comment by pentiminax** [comment]
I can confirm that I see the error on my side too with 

- symfony/twig-bridge 7.2.0 (9958f5a5b6640734fe4b24c18897191f77a02c61) and
-  EasyAdminBundle 4.18.0 (c1b694c1890d6f20858802d201cd7199212dc42a)
- twig/twig 3.16.0 (9746573ca4bc1cd03a767a183faadaf84e0c31fa)

![image](https://github.com/user-attachments/assets/90894010-a64e-42df-9ea8-fca6b9dc6c96)

**Comment by pan93412** [comment]
> @javiereguiluz Can you check that you have version 3.16.0?

The `composer.lock` indeed indicates that it is on Twig 3.16.0:

https://github.com/javiereguiluz/ea-bug-reproducer/blob/0467a4bb1a9a37e28b1a091f6509b1521d2217bb/composer.lock#L7773-L7779

Note that I am using the latest Twig and `symfony/twig-bridge` (6cc64f2357382540eeac5b2f66fc44fd34298693 and https://github.com/symfony/twig-bridge/commit/9958f5a5b6640734fe4b24c18897191f77a02c61), and it is also reproducible.

![CleanShot 2024-12-01 at 22 39 03@2x](https://github.com/user-attachments/assets/52d9f5cb-7378-42e4-8d1e-21170383b0f4)

**Comment by javiereguiluz** [comment]
@fabpot I made several tests:

| EA version | SF version | Result
| ---------- | ---------- | ------
| 4.18.0 | 7.2.0 | ❌ Fails
| 4.15.1 | 7.2.0 | ❌ Fails
| 4.18.0 | 7.1.9 | ✅ Works
| 4.15.1 | 7.1.9 | ✅ Works

EA 4.16.0 introduced Twig Components; that's why I also test 4.15.1.

I did another test: EA 4.18 + SF 7.2 works if I downgrade Twig to 3.14.2. The first version that doesn't work is Twig 3.15.0.

**Comment by xabbuh** [comment]
I am looking into it.

**Comment by bilik** [comment]
> Closing as this has been fixed already as mentioned above.

This closure was not fixed as mentioned above.

**Comment by ericmorand** [comment]
> This closure was not fixed as mentioned above.

Be prepared for the "acceptable breaking change" excuse.

**Comment by alexislefebvre** [comment]
Do you have the same issue when using `APP_ENV=prod`? It sort of "*fixes*" the error on local environment. And when the project is deployed to prod, the admin works without any issue. Is the warning silenced on `prod` environment?

Update: yes it appears in the logs:

```
{"message":"Warning: Undefined variable $_v0","context":{"exception":{"class":"ErrorException","message":"Warning: Undefined variable $_v0","code":0,"file":"[…]/releases/366/var/cache/prod/twig/99/99e1019c709c6dad46cac106a8bf70d9.php:741"}},"level":400,"level_name":"ERROR","channel":"php","datetime":"2024-12-01T20:05:04.074353+01:00","extra":{}}
```

**Comment by fabpot** [comment]
> > This closure was not fixed as mentioned above.
> 
> Be prepared for the "acceptable breaking change" excuse.

Please, be respectful. This comment is inappropriate, even more so as @xabbuh commented that he was looking at it.

**Comment by ericmorand** [comment]
How is that inappropriate? It is exactly the excuse that your team used about another closed issue. Is this is inappropriate here, it was also inappropriate when your team used it.

Also note that this issue is still closed. If someone was looking at it, it would have been reopened.

**Comment by bilik** [comment]
> > > This closure was not fixed as mentioned above.
> > 
> > 
> > Be prepared for the "acceptable breaking change" excuse.
> 
> Please, be respectful. This comment is inappropriate, even more so as @xabbuh commented that he was looking at it.

Why isn't it reopen? I don't use EasyAdmin and I have the same problem.

**Comment by pan93412** [comment]
> Why isn't it reopen?

I believe they are trying to figure out whether the issue lies with EasyAdmin or Twig.

**Comment by fabpot** [comment]
Maybe because the discussion happened during the week-end?

**Comment by xabbuh** [comment]
Can everyone affected by this issue please check if symfony/symfony#59059 fixes it?

**Comment by q1t1** [comment]
> Can everyone affected by this issue please check if [symfony/symfony#59059](https://github.com/symfony/symfony/pull/59059) fixes it?

It is still present

**Comment by xabbuh** [comment]
@q1t1 Can you create a small example application that allows to reproduce your issue then please?

**Comment by javiereguiluz** [comment]
@xabbuh yes, your change fixed the issue to me 🎉 

Now I have SF 7.2.0 + Twig 3.16.0 + EA 4.18.0 and it's working 🙌  Thanks a lot 🙇

**Comment by q1t1** [comment]
> @q1t1 Can you create a small example application that allows to reproduce your issue then please?

Unfortunately, not at this time...

But I have SF 7.2.0 + Twig 3.16.0 + EA 4.18.0 too, and it doesn't work
If I downgrade to Twig 3.14.2, it is OK

**Comment by javiereguiluz** [comment]
In addition to the reproducer app, I just tested this on a real and complex Symfony app that was failing too, and the changes proposed by Christian fixed it too.

@q1t1 probably you did, but make sure to run `rm -fr var/cache/*` and `symfony server:stop && symfony serve -d` after changing that file in `vendor/symfony/twig-bridge/NodeVisitor/TranslationDefaultDomainNodeVisitor.php`

**Comment by xdrew** [comment]
> Can everyone affected by this issue please check if [symfony/symfony#59059](https://github.com/symfony/symfony/pull/59059) fixes it?

Mine issue also gone for SF 7.2.0 + Twig 3.16.0 + EA 4.18.0. Thanks

**Comment by RibJulien** [comment]
> Can everyone affected by this issue please check if [symfony/symfony#59059](https://github.com/symfony/symfony/pull/59059) fixes it?

Fix works for me with SF 7.2.0, Twig 3.16.0, EA 4.18.0

**Comment by fracsi** [comment]
> Can everyone affected by this issue please check if [symfony/symfony#59059](https://github.com/symfony/symfony/pull/59059) fixes it?

SF 7.2.0, Twig 3.15.0 / 3.16.0, EasyAdmin 4.18.0 - fix works

**Comment by q1t1** [comment]
I managed to get it to work, thank you !

**Comment by fabpot** [comment]
Thank you all for confirming.

**Comment by pan93412** [comment]
I have some tough time merging the commit to 7.3. I would try it later when this commit ported to 7.3.

![CleanShot 2024-12-02 at 20 35 49@2x](https://github.com/user-attachments/assets/c3080b1c-22bd-47d8-9002-922e3e626be4)

**Comment by xabbuh** [comment]
@pan93412 done

**Comment by pan93412** [comment]
> @pan93412 done

Works on https://github.com/symfony/twig-bridge/commit/1343696b988e72beafc63a6cf386922ccb314a08, https://github.com/twigphp/Twig/commit/57bf519af2bd60fe181fd632bd268e73daab807f, and https://github.com/EasyCorp/EasyAdminBundle/commit/2307da58ccfd0569f65943b9a01d49a4f3a71d7d. Thanks!

**Comment by alexislefebvre** [comment]
> I have some tough time merging the commit to 7.3. I would try it later when this commit ported to 7.3.

7.3 will be released on 2025: https://symfony.com/releases/7.3

**Comment by pan93412** [comment]
> > I have some tough time merging the commit to 7.3. I would try it later when this commit ported to 7.3.
> 
> 7.3 will be released on 2025: https://symfony.com/releases/7.3

I know. I have already adapted my project to 7.3-DEV.

**Comment by siggidiel** [comment]
Unfortunately, this is still happening. Even with Symonfy 7.2 + EA 4.18 + Twig 3.16. The only fix here is to go back to `twig/twig` version `3.14.2`.

**Comment by jdreesen** [comment]
You did manually apply the patch, right? Because the fix is not yet released.

**Comment by stof** [comment]
@ServerExe are you using the 7.2.x-dev version of Symfony or a stable release ? The fix has been merged in Symfony (hence closing the bug) but not yet released.

**Comment by siggidiel** [comment]
No, I am using the stable version of 7.2. Not the dev one. Okay, so it's not yet released, got it :) Thank you!

**Comment by LaurentMarquet** [comment]
Hi, has someone found a solution? Because using SF 7.2.0, Twig 3.16.0 and EasyAdmin 4.20.0 I still have the same problem

**Comment by javiereguiluz** [comment]
@LaurentMarquet this is a known problem of Symfony 7.2.0.

The bug has been fixed here: https://github.com/symfony/symfony/pull/59059 but it won't be available until Symfony 7.2.1 is released.

**Comment by ericmorand** [comment]
@fabpot 

> Maybe because the discussion happened during the week-end?

And maybe it would not happen if you stopped introducing breaking changes into minor versions. Using the weekend excuse as a way to hide the fact that you don't care about us is disrespectful. I will say again in case today you are ready to listen: just emit a major version whenever you introduce breaking changes. We are not your beta testers.

**Comment by pan93412** [comment]
> > 
> 
> And maybe it would not happen if you stopped introducing breaking changes into minor versions. Using the weekend excuse as a way to hide the fact that you don't care about us is disrespectful. I will say again in case today you are ready to listen: just emit a major version whenever you introduce breaking changes. We are not your beta testers.

I believe this is more of a bug than an intended breaking change. 

I noticed this issue during the 7.2 beta as well, but I'm not sure if it's caused by EasyAdmin, Twig, or Symfony, so I didn't report it. Is there a chatroom or a place where I can submit a general bug report that can be discussed before creating an actual bug report? I'm unsure if Symfony's Slack is active.

**Comment by endroid** [comment]
@ericmorand If you eat an apple from a tree and find a worm in it, don't blame the tree

**Comment by javiereguiluz** [comment]
@pan93412 yes, it'd be very useful to us if you reported this issue when you found it. Next time, please do. Don't worry about reporting the issue in the "wrong" repository; we'll guide you, if needed, to open the issue in the most appropriate repository.

About https://symfony.com/slack activity, I can tell you that it's more active than ever so you can use that too if you prefer it. Thanks.

**Comment by stof** [comment]
@ericmorand this bug was **not** caused by a BC break at all.
We did a refactoring in the implementation of `{% trans_default_domain %}` in `symfony/twig-bridge` and the new implementation had a bug (not intended at all) in a case that was not covered by an integration test of the feature (new tests have also been added to prevent this to happen again in the future). The reason why downgrading Twig also fixed the issue is because the internal implementation of Symfony switches between 2 implementations depending on the version of Twig to avoid reporting a deprecation warning, and the bug was only in 1 of them, not in both.

**Comment by Kelaven** [comment]
> Can everyone affected by this issue please check if [symfony/symfony#59059](https://github.com/symfony/symfony/pull/59059) fixes it?

It works for me, thank you ! 🎼

**Comment by fabpot** [comment]
Symfony 7.2.1 has been released.
